### ISSUE TITLE
Publish on Open VSX Registry (Add GitPod, VSCodium support)

### ISSUE THREAD

**Issue by michoelchaikin** [egomobile/vscode-powertools#6]
Is it possible for this extension to be published to Open VSX?

Open XSV is a vendor-neutral, open-source alternative marketplace for VS Code Extensions. Adding the extension to this registry will allow it to be used in fully open-source forks of VS Code such as VSCodium, gitpod etc.

Further information for publishing extensions to the registry is available here: https://github.com/eclipse/openvsx/wiki/Publishing-Extensions

**Comment by mkloubertego** [comment]
@michoelchaikin 

Of course :-) https://open-vsx.org/extension/egomobile/vscode-powertools

We also added this to our default build and deploy process: https://github.com/egomobile/vscode-powertools/blob/ce80847c9c8240e36f188da85528c2242a8890e7/deploy.js#L30

Keep in mind: From v0.67.1 on, a version, which is compatible to VSCode 1.62, is required.

**Comment by michoelchaikin** [comment]
@mkloubertego Wow thanks for doing this so quickly! I'm loving this extension 😃
